name: Docker image build and push
on:
  schedule:
    - cron: "0 4 * * 2,6"
  workflow_dispatch:
jobs:
  docker-push:
    name: Docker image build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      - name: Build docker image and push it, if new tag available
        run: bash ./push.sh
